name: deploy-firebase-staging-action

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@main
        
      - name: "Build Node"
        uses: actions/setup-node@v2
        with: 
          node-version: 12
      - run: cd functions && npm install
      - run: cd functions && npm run build
      
      - name: "Deploy Firebase"
        uses: doonstore/firebase-deploy@v1
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: ${{ secrets.FIREBASE_STAGING_PROJECT }}
      
